cartogram: main.cpp read_geojson.cpp read_geojson.h geo_div.cpp geo_div.h\
	 read_csv.cpp read_csv.h
	g++ -O3 -o cartogram main.cpp read_geojson.cpp geo_div.cpp read_csv.cpp -lboost_program_options -lCGAL -lgmp
