name: CI

on:
  push:
    branches: [ "main","github-actions-python"]
    paths: ['**.json', '**.geojson']

jobs:
  build:
    runs-on: ubuntu-latest  
    name: get changed files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3 

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: BSFishy/pip-action@v1
        with: 
           packages: |
            jsonschema2md
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import json
            import jsonschema2md
            
            parser = jsonschema2md.Parser(
                examples_as_yaml=False,
                show_examples="all",
                )
            with open("./testing.json", "r") as json_file:
            md_lines = parser.parse_schema(json.load(json_file))
            print(''.join(md_lines))