name: Json_to_md

on:
  push:
    branches: [ "main","github-actions-python"]
    paths: ['**.json', '**.geojson']

jobs:
  changes:
    runs-on: ubuntu-latest  
    name: add markdown documentation
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed .json files with paths
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3 
        with:
          files: |
            ./**
            *.json
            *.geojson
            

      - name: Get changed directory paths
        id: changed-directories-of-files
        uses: tj-actions/changed-files@v29.0.3 
        with:
          files: |
            ./**
            *.json
            *.geojson
          dir_names: "true"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "$file was changed"
          done
      
      - name: Create empty markdown file in folder
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: "./${{ steps.changed-directories-of-files.outputs.all_modified_files }}/documentation.md"
      
      - name: Setup Python 
        uses: actions/setup-python@v2


      - name: Setup jsonschema2md Package
        uses: BSFishy/pip-action@v1
        with: 
           packages: |
            jsonschema2md
      
      - name: Write to Markdown
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import json
            import jsonschema2md

            parser = jsonschema2md.Parser(
                examples_as_yaml=False,
                show_examples="all",
                )
            with open("${{ steps.changed-json-files-with-paths.outputs.all_modified_files }}") as json_file, open("./${{ steps.changed-directories-of-files.outputs.all_modified_files }}/documentation.md", 'w') as output_markdown:
                output_md = parser.parse_schema(json.load(json_file))
                output_markdown.writelines(output_md)
      
      - name: Push changed and added files to repo
        uses: EndBug/add-and-commit@v9.1.0
      
      

