name: Bibtex_to_md

on:
  push:
    branches: [ "main","github-autodocs-bibtex"]
    paths: ['**.bib']

jobs:
  changes:
    runs-on: ubuntu-latest  
    name: add html documentation
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed directory paths
        id: changed-directories-of-files
        uses: tj-actions/changed-files@v29.0.3 
        with:
          files: |
            ./**
            *.bib
          dir_names: "true"
      
      - name: Run Pandoc Converter and create html file
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            --filter=pandoc-citeproc 
            --standalone 
            ./sample_data/templates/html_converter.bib
            -o 
            ./${{ steps.changed-directories-of-files.outputs.all_changed_files }}/documentation.html
            
      
      - name: Push changed and added files to repo
        uses: EndBug/add-and-commit@v9.1.0
      

