name: CI

on:
  push:
    branches: [ "main","github-action-blah"]
    paths: ['**.json', '**.geojson']

jobs:
  build:
    runs-on: ubuntu-latest  
    name: get changed files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3 

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  generate:
    runs-on: ubuntu-latest
    name: Generate markdown
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install blah
        id: blah-install
        run: npm install --global blah

      - name: Generate documentation
        id: documentation
        run: blah --docs(testing.json)