name: Bibtex_to_md

on:
  push:
    branches: [ "main","github-autodocs-bibtex"]
    paths: ['**.bib']

jobs:
  changes:
    runs-on: ubuntu-latest  
    name: add markdown documentation
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed .json files with paths
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3 
        with:
          files: |
            ./**
            *.bib
            

      - name: Get changed directory paths
        id: changed-directories-of-files
        uses: tj-actions/changed-files@v29.0.3 
        with:
          files: |
            ./**
            *.bib
          dir_names: "true"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      
      - name: Create empty markdown file in folder
        uses: 1arp/create-a-file-action@0.2
        with:
          path: './${{ steps.changed-directories-of-files.outputs.all_changed_files }}'
          file: 'testing.md'
          content: |
            ---
            bibliography: testing.bib
            nocite: '@*'
            ...

            #Bibliography
      
      - name: Run Pandoc Converter
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            --filter=pandoc-citeproc 
            --standalone 
            testing.md 
            --o 
            testing.html
      
      

